export enum WAEvent {
  CONNECTION_UPDATE = 'connection.update',
  CREDS_UPDATE = 'creds.update',
  CHATS_SET = 'chats.set',
  CHATS_UPDATE = 'chats.update',
  CHATS_UPSERT = 'chats.upsert',
  CHATS_DELETE = 'chats.delete',
  CONTACTS_SET = 'contacts.set',
  CONTACTS_UPDATE = 'contacts.update',
  CONTACTS_UPSERT = 'contacts.upsert',
  CONTACTS_DELETE = 'contacts.delete',
  MESSAGES_SET = 'messages.set',
  MESSAGES_DELETE = 'messages.delete',
  MESSAGES_UPDATE = 'messages.update',
  MESSAGES_UPSERT = 'messages.upsert',
  MESSAGES_MEDIA_UPDATE = 'messages.media-update',
  MESSAGES_REACTION = 'messages.reaction',
  MESSAGES_RECEIPT_UPDATE = 'messages-receipt.update',
  GROUPS_UPSERT = 'groups.upsert',
  GROUPS_UPDATE = 'groups.update',
  GROUP_PARTICIPANTS_UPDATE = 'group-participants.update',
  BLOCKLIST_SET = 'blocklist.set',
  BLOCKLIST_UPDATE = 'blocklist.update',
  CALL = 'call'
}
